ignore:
  field_paths:
    - CreateUserInput.ServerId
    - CreateUserInput.UserName
    - CreateUserInput.Role
    - CreateServerInput.EndpointDetails
    - CreateServerInput.Certificate
    - CreateServerInput.LoggingRole
resources:
  Server:
    exceptions:
      errors:
        404:
          code: ResourceNotFoundException
  User:
    exceptions:
      errors:
        404:
          code: ResourceNotFoundException    
